name: Maintenance Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # At midnight every day (UTC time)

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Enable GitHub Pages
      run: |
        git checkout main
        git checkout -b gh-pages
        git push origin gh-pages

    - name: Disable GitHub Pages
      run: |
        git checkout main
        git push origin --delete gh-pages
